name: aqim
description: "أقم — مدرب شخصي لبناء عادة الصلاة"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  dependencies:
  
  audioplayers: ^6.0.0
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/before/
    - assets/audio/after/
